export enum Attribute {
  Accountability = 'Accountability',
  Assertiveness = 'Assertiveness',
  Building_Relationships = 'Building relationships',
  Cognitive_Ability = 'Cognitive ability',
  Consultation = 'Consultation',
  Dedication_And_Commitment = 'Dedication and commitment',
  Delegation = 'Delegation',
  Efficiency = 'Efficiency',
  Empowering = 'Empowering',
  Motivation = 'Motivation',
  Flexibility = 'Flexibility',
  Negotiation = 'Negotiation',
  Deal_Making = 'Deal making',
  Openness = 'Openness',
  Political_Awareness = 'Political awareness',
  Public_Speaking = 'Public speaking',
  Relaxation = 'Relaxation',
  Reliability = 'Reliability',
  Self_Management = 'Self management',
  Values_Appreciation = 'Values appreciation',
  Vision_And_Imagination = 'Vision and imagination',
  Presentation_Skills = 'Presentation skills'
}
